# Generated by Django 4.1.7 on 2023-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_menber_name_alter_menber_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menber',
            name='andress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
